name: riba
description: Cross-platform mobile client for MangaDex
version: 1.0.0+1
publish_to: "none"

environment:
    sdk: ">=3.0.0"

dependencies:
    animations: ^2.0.7
    copy_with_extension: ^5.0.2
    dash_flags: ^0.1.1
    dynamic_color: ^1.6.5
    fl_chart: ^0.62.0
    flutter:
        sdk: flutter
    flutter_animate: ^4.1.1+1
    google_fonts: ^4.0.4
    http: ^0.13.6
    intl: ^0.18.1
    isar: ^3.1.0+1
    isar_flutter_libs: ^3.1.0+1
    json_annotation: ^4.8.1
    logging: ^1.1.1
    meta: ^1.9.1
    package_info_plus: ^4.0.0
    path_provider: ^2.0.15
    rxdart: ^0.27.7
    url_launcher: ^6.1.11

dev_dependencies:
    build_runner: ^2.4.4
    copy_with_extension_gen: ^5.0.2
    flutter_launcher_icons: ^0.13.1
    flutter_lints: ^2.0.1
    flutter_test:
        sdk: flutter
    isar_generator: ^3.1.0+1
    json_serializable: ^6.6.2

flutter:
    uses-material-design: true
